OTDM/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTDM.Models;
using OTDM.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;

namespace OTDM.Controllers
{
    public class ActivitiesController : Controller
    {
        private ApplicationDbContext _context;

        public ActivitiesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Activities
        public ActionResult MyActivities()
        {
            IEnumerable<Request> myActiveTasks;
            var currentUser = User.Identity.GetUserId();
            var isAdmin = User.IsInRole(RoleName.Admin);
            var isQualityManager = User.IsInRole(RoleName.QualityManager);
            var isTechnicalInvestigator = User.IsInRole(RoleName.TechnicalInvestigator);

            if (isAdmin)
                myActiveTasks = _context.Requests.Where(r => r.RequestStatus != RequestStatusEnum.Completed && r.RequestStatus != RequestStatusEnum.WaitingForCollection && isAdmin).Include(r => r.RequestedDevice).ToList();
            else if (isQualityManager)
                myActiveTasks = _context.Requests.Where(r => r.RequestStatus == RequestStatusEnum.WaitingForCollection && r.RequesterId == currentUser && isQualityManager).Include(r => r.RequestedDevice).ToList();
            else
                myActiveTasks = Enumerable.Empty<Request>();
            var viewModel = new MyActivitiesViewModel
            {

                MyActiveTasks = myActiveTasks,
                MyArchivedTasks = _context.Requests.Where(r => r.GiverId == currentUser || r.ReceiverId == currentUser && r.RequestStatus == RequestStatusEnum.Completed).Include(r => r.RequestedDevice).ToList(),
                MyActiveRequests = _context.Requests.Where(r => r.RequestStatus != RequestStatusEnum.Completed && r.RequesterId == currentUser).Include(r => r.RequestedDevice).ToList(),
                MyArchivedRequests = _context.Requests.Where(r => r.RequestStatus == RequestStatusEnum.Completed && r.RequesterId == currentUser).Include(r => r.RequestedDevice).ToList(),
                ProblemsToResolve = _context.Problems.Where(p => p.ProblemStatus != ProblemStatusEnum.Resolved && (isAdmin || isTechnicalInvestigator)).Include(p=>p.Device).ToList(),
                ProblemsReportedByMe = _context.Problems.Where(p => p.ReporterId == currentUser).Include(p => p.Device).ToList()

            };
            return View(viewModel);
        }
    }
}

OTDM/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTDM.Models;
using OTDM.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System.Data.Entity;

namespace OTDM.Controllers
{
    [Authorize(Roles = RoleName.Admin)]
    public class PermissionsController : Controller
    {
        private ApplicationDbContext _context;
        private ApplicationUserManager _userManager;


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public PermissionsController()
        {
            _context = new ApplicationDbContext();
        }

        public PermissionsController(ApplicationUserManager userManager)
        {
            _context = new ApplicationDbContext();
            UserManager = userManager;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Permissions
        public ActionResult AllPermissions()
        {

            var allUsers = _context.Users.ToList();
            var users = allUsers
                        .Select(u => new PermissionViewModel
                        {
                            User = u,
                            RolesList = _context.Roles
                            .Where(role => role.Users.Any(user => user.UserId == u.Id))
                            .ToList()
                        });
                  

            return View(users);

        }

        public ActionResult ManagePermissions(string id)
        {
            if (id == null)
                return RedirectToAction("AllPermissions");

            var viewModel = new PermissionViewModel
            {
                User = _context.Users.SingleOrDefault(u => u.Id == id),
                RolesList = _context.Roles.ToList(),
                RolesCheckBoxes = new Dictionary<string, bool>()
            };
            
            foreach(var role in viewModel.RolesList)
            {
                viewModel.RolesCheckBoxes.Add(role.Name, viewModel.User.Roles.Any(r => r.RoleId == role.Id));
            }


            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Update (PermissionViewModel viewModel)
        {

            var formCheckboxes = viewModel.RolesCheckBoxes;
            foreach (var checkbox in formCheckboxes)
            {
                if (checkbox.Value == true)
                {
                    UserManager.AddToRole(viewModel.User.Id, checkbox.Key);
                }

                else
                {
                    UserManager.RemoveFromRole(viewModel.User.Id, checkbox.Key);
                }

            }
            return RedirectToAction("AllPermissions");
        }
    }
}

OTDM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Omega Devices</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
                <div class="container body-content">
                    <a style="margin-top:20px;" class="btn btn-info pull-right" id="backbutton" href=@Request.UrlReferrer>
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    @RenderBody()
                    
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Piotr Majewski</p>
                    </footer>
                </div>

                @Scripts.Render("~/bundles/lib")
                @RenderSection("scripts", required: false)
    </body>
</html>

OTDM/Views/Shared/_NavBar.cshtml
@using Microsoft.AspNet.Identity;
@using OTDM.Models;

<div class="navbar navbar-inverse navbar-fixed-top">
    <a href="/Home/Index"><img class="navbar-brand" src="~/Content/images/_sitelogo.jpg"></a>
     <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

            @if (Request.IsAuthenticated)
            {
                <li>
                    <a class = "nav-link" href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Informacje</a>
                </li>
                <li>
                    <a class = "nav-link" href="@Url.Action("MyActivities", "Activities")"><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> Moje Aktywności</a>
                </li>
                <li>
                    <a class = "nav-link" href="@Url.Action("Index", "Devices")"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Urządzenia kontrolno-pomiarowe</a>
                </li>
                if (User.IsInRole(RoleName.Admin))
                {
                    <li>
                        <a class="nav-link" href="@Url.Action("AllPermissions", "Permissions")"><span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span> Uprawnienia</a>
                    </li>
                }

            }
            else
            {
                <li>
                    <a class="nav-link" href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Informacje</a>
                </li>
            }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>