OTDM/Models/Request.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace OTDM.Models
{
    public class Request
    {
        public int Id { get; set; }

        public ApplicationUser Requester { get; set; }

        [Required]
        public string RequesterId { get; set; }

        [Display(Name ="Użytkownicy produkcyjni")]
        public string ProductionUser { get; set; }

        public ApplicationUser Giver { get; set; }
        public string GiverId { get; set; }

        [Required]
        [Display(Name = "Estymowany czas zwrotu")]
        public DateTime? EstimatedUsageTime { get; set; }

        public ApplicationUser Receiver { get; set; }
        public string ReceiverId { get; set; }

        [Required]
        [Display(Name = "Numer zamówienia produkcyjnego")]
        public string OrderId { get; set; }
        
        public Device RequestedDevice { get; set; }

        [Required]
        public int RequestedDeviceId { get; set; }

        [Required]
        [Display(Name = "Data rozpoczęcia produkcji")]
        public DateTime? StartingDate { get; set; }

        public DateTime? EndDate { get; set; }

        public string Comment { get; set; }

        public RequestStatusEnum RequestStatus { get; set; } = RequestStatusEnum.WaitingForAction;
        
    }

    public enum RequestStatusEnum
    {
        WaitingForAction = 1,
        WaitingForCollection = 2,
        InUse = 3,
        Completed = 4
    }

}

OTDM/Controllers/Api/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using OTDM.Models;
using OTDM.Dtos;
using AutoMapper;
using OTDM.Models.ViewModels;

namespace OTDM.Controllers.Api
{
    public class RequestsController : ApiController
    {
        private ApplicationDbContext _context;

        public RequestsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET /api/Requests
        public IEnumerable<RequestDto> GetRequests()
        {
            return _context.Requests.ToList().Select(Mapper.Map<Request, RequestDto>);
        }

        //GET /api/Requests/id

        public RequestDto GetRquest(int id)
        {
            var request = _context.Requests.SingleOrDefault(r => r.Id == id);
            if (request == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            return Mapper.Map<Request, RequestDto>(request);

        }

        //POST /api/Requests
        [HttpPost]
        public RequestDto CreateRequest(RequestDto requestDto)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }
            _context.Requests.Add(Mapper.Map<RequestDto, Request>(requestDto));
            _context.SaveChanges();
            return requestDto;      
        }

        //PUT /api/Request/id
        [HttpPut]
        public void UpdateRequest(int id, RequestDto requestDto)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }
            else
            {
                var request = _context.Requests.SingleOrDefault(r => r.Id == id);
                if (request == null)
                    throw new HttpResponseException(HttpStatusCode.NotFound);
                Mapper.Map(request, requestDto);
                _context.SaveChanges();
            }

        }

        //Delete /api/Request/id
        [HttpDelete]
        public void RemoveRequest(int id)
        {
            var request = _context.Requests.SingleOrDefault(r => r.Id == id);
            _context.Requests.Remove(request);
            _context.SaveChanges();
        }
    }
}

OTDM/Controllers/ReassignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTDM.Models;
using OTDM.Models.ViewModels;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace OTDM.Controllers
{
    [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager + "," + RoleName.Auditor + "," + RoleName.TechnicalInvestigator)]
    public class ReassignmentsController : Controller
    {
        private ApplicationDbContext _context;
        private ApplicationUserManager _userManager;


        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ReassignmentsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Reassignments
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult ReassignDeviceForm(int id)
        {
            if (_context.Requests.Any(r => r.Id == id && r.RequestStatus == RequestStatusEnum.Completed))
                throw new InvalidOperationException("Niepoprawna operacja");

            else if (_context.Requests.SingleOrDefault(r => r.Id == id).RequesterId != User.Identity.GetUserId() && !User.IsInRole(RoleName.Admin))
                throw new InvalidOperationException("Nie masz uprawnień do przekazania tego testera (nie jesteś w jego posiadaniu, lub nie masz uprawnień administratora)");

            var viewModel = new ReassignFormViewModel
            {
                Reassignment = new Reassignment
                {
                    RequestId = id,
                    ReassignmentDate = DateTime.Now,
                    ReassignedFrom = _context.Requests.SingleOrDefault(r=>r.Id==id).RequesterId
                },

                RequestersList = _context.Users.ToList()
            };
            return View(viewModel);
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult CreateReassignment(ReassignFormViewModel viewModel)
        {
            if (_context.Requests.Any(r => r.Id == viewModel.Reassignment.RequestId && r.RequestStatus == RequestStatusEnum.Completed))
                throw new InvalidOperationException("Niepoprawna operacja");
            else if (_context.Requests.SingleOrDefault(r => r.Id == viewModel.Reassignment.RequestId).RequesterId != User.Identity.GetUserId() && !User.IsInRole(RoleName.Admin))
                throw new InvalidOperationException("Nie masz uprawnień do przekazania tego testera (nie jesteś w jego posiadaniu, lub nie masz uprawnień administratora)");

            else if (!ModelState.IsValid)
            {
                var validatedViewModel = new ReassignFormViewModel();
                validatedViewModel = viewModel;
                return View("ReassignDeviceForm", viewModel);
               
            }
            else
            {
                _context.Reassignments.Add(viewModel.Reassignment);
                _context.Requests.SingleOrDefault(r => r.Id == viewModel.Reassignment.RequestId).RequesterId = viewModel.Reassignment.ReassignedTo;
                _context.SaveChanges();
                return RedirectToAction("MyActivities", "Activities");
            }
        }

        public ActionResult ReassignmentsHistory(int id)
        {
            var viewModel = new ReassignmentsHistoryViewModel
            {
                ReassignmentsList = _context.Reassignments.Where(r => r.RequestId == id).ToList(),
                ViewUserManager = UserManager

            };
            
            return View(viewModel);
        }
    }
}

OTDM/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTDM.Models;
using OTDM.Models.ViewModels;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using OTDM.Util;

namespace OTDM.Controllers
{
    [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager + "," + RoleName.Auditor + "," + RoleName.TechnicalInvestigator)]
    public class RequestsController : Controller
    {

        private ApplicationDbContext _context;

        public RequestsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        public ActionResult Index()
        {
            var requestsList = _context.Requests.Include("RequestedDevice").ToList();
            if (User.IsInRole(RoleName.Admin))
                return View("Index_Admin", requestsList);
            else if (User.IsInRole(RoleName.Auditor))
                return View("Index_Auditor", requestsList);
            else return View("Index_Requester", requestsList);
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult RequestDevice(int? id)
        {

            if (id == null)
                return RedirectToAction("Index");

            else if (!_context.Devices.SingleOrDefault(d => d.Id == id).IsValidated || _context.Devices.SingleOrDefault(d=>d.Id == id).NextValidationDate <= DateTime.Now)
                throw new InvalidOperationException("Tester nie został jeszcze zwalidowany lub jest sparwdzany przez dział techniczny w związku ze zgłoszoniem problemu");

            else if (_context.Requests.Any(r => r.RequestedDeviceId == id && r.RequestStatus != RequestStatusEnum.Completed))
                throw new InvalidOperationException("Ten tester jest obecnie w użyciu");

            else
            {
                var viewModel = new RequestFormViewModel
                {
                    Request = new Request
                    {
                        RequestedDeviceId = (int)id,
                        RequesterId = User.Identity.GetUserId()
                    },     
                    
                    RequesterName = User.Identity.GetUserName(),
                    DeviceName = _context.Devices.SingleOrDefault(d => d.Id == id).Name

                };
                return View(viewModel);
            }      
            
        }
        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult CreateRequest(RequestFormViewModel viewModel)
        {
            var deviceInDb = _context.Devices.SingleOrDefault(d => d.Id == viewModel.Request.RequestedDeviceId);
            if ((_context.Requests.Any(r => r.RequestedDeviceId == viewModel.Request.RequestedDeviceId && r.RequestStatus != RequestStatusEnum.Completed)))
                throw new InvalidOperationException("Ten tester jest obecnie w użyciu");
            else if (!ModelState.IsValid)
            {
                var validatedViewModel = new RequestFormViewModel();
                validatedViewModel = viewModel;
                return View("RequestDevice", validatedViewModel);
            }

            _context.Requests.Add(viewModel.Request);
            _context.SaveChanges();

            MailSender.SendMail(GroupMails.ProductionGroupMail, GroupMails.QualityGroupMail, "Prośba o przygotowanie urządzenia",
                                viewModel.RequesterName + " poprosił o przygotowanie urządzenia: " + viewModel.DeviceName + " - " +viewModel.Request.RequestedDevice.Code + " w związku ze zleceniem produkcyjnym: " + viewModel.Request.OrderId +
                                ". Czas rozpoczęcia produkcji: " + viewModel.Request.StartingDate + ". Estymowany czas zakonczenia użytkowania: " + viewModel.Request.EstimatedUsageTime);

            return RedirectToAction("Index", "Devices");
        }

        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Prepared(int id)
        {
            var requestInDb = _context.Requests.Include(r=>r.RequestedDevice).SingleOrDefault(r => r.Id == id);
            if (requestInDb.RequestStatus != RequestStatusEnum.WaitingForAction)
                throw new InvalidOperationException("Niepoprawna operacja");
            else
            {
                requestInDb.RequestStatus = RequestStatusEnum.WaitingForCollection;
                requestInDb.GiverId = User.Identity.GetUserId();
            }

            _context.SaveChanges();

            MailSender.SendMail(GroupMails.QualityGroupMail, GroupMails.ProductionGroupMail, "Urządzenie oczekuje na odbiór", 
                "Urządzenie: " + requestInDb.RequestedDevice.Name + " o kodzie: " + requestInDb.RequestedDevice.Code + " zamówione do zlecenia produkcyjnego: " + requestInDb.OrderId + " oczekuje na odbiór lidera.");

            return RedirectToAction("MyActivities", "Activities");
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult Collected(int id)
        {
            if (_context.Requests.Any(r => r.Id == id && r.RequestStatus != RequestStatusEnum.WaitingForCollection))
                throw new InvalidOperationException("Niepoprawna operacja");
            else
            {
                var requestInDb = _context.Requests.SingleOrDefault(r => r.Id == id);
                requestInDb.RequestStatus = RequestStatusEnum.InUse;
                
            }
            _context.SaveChanges();
            return RedirectToAction("MyActivities", "Activities");
        }

        [Authorize(Roles = RoleName.Admin)]
        public ActionResult CommentForm(int id)
        {
            if (_context.Requests.Any(r => r.Id == id && r.RequestStatus == RequestStatusEnum.Completed))
                throw new InvalidOperationException("To zamówienie zostało już zakonczone");
            else
            {
                var viewModel = new RequestCompletetedCommentViewModel
                {
                    RequestId = id,

                };
                return View(viewModel);
            }
                
        }

        [Authorize(Roles = RoleName.Admin)]
        public ActionResult UnblockDevice(RequestCompletetedCommentViewModel viewModel)
        {
            if (_context.Requests.Any(r => r.Id == viewModel.RequestId && r.RequestStatus == RequestStatusEnum.Completed))
                throw new InvalidOperationException("To zamówienie zostało już zakonczone");
            else
            {
                var requestInDb = _context.Requests.SingleOrDefault(r => r.Id == viewModel.RequestId);
                requestInDb.RequestStatus = RequestStatusEnum.Completed;
                requestInDb.ReceiverId = User.Identity.GetUserId();
                requestInDb.EndDate = DateTime.Now;
                requestInDb.Comment = viewModel.Request.Comment;

                _context.SaveChanges();

            }
            return RedirectToAction("MyActivities", "Activities");


        }

      
    }
}

OTDM/Views/Requests/CommentForm.cshtml
@model OTDM.Models.ViewModels.RequestCompletetedCommentViewModel
@{
    ViewBag.Title = "Comment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Twój komentarz</h2>

@using (Html.BeginForm("UnblockDevice", "Requests"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Request.Comment)
        @Html.TextAreaFor(m =>m.Request.Comment, new {@class = "form-control", style = "min-height:200px;" })
    </div>
    @Html.HiddenFor(m =>m.RequestId)
    <button type="submit" class="btn btn-primary">Potwierdź odbiór</button> @Html.ActionLink("Anuluj", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-warning" })
}

OTDM/Views/Requests/Index_Admin.cshtml
@using OTDM.Models
@model IEnumerable<Request>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Wszystkie zamówienia</h2>

    <table class="dtable table table-striped table-bordered nowrap" cellspacing="0" width="100%">
    <thead class="thead-dark">
        <tr>
            <th>Numer zamówienia</th>
            <th>Nazwa urządzenia</th>
            <th>Status</th>
            <th>Pzrekazania</th>
            <th>Akcje do podjęcia</th>
        </tr>

    </thead>

    <tbody>

        @foreach (var req in Model)
        {
            <tr>
                <td>@req.Id</td>
                <td>@req.RequestedDevice.Name</td>
                <td>@req.RequestStatus</td>
                <td>@Html.ActionLink("Zobacz", "ReassignmentsHistory", "Reassignments", new { id = req.Id }, null)</td>
                @switch (req.RequestStatus)
                {
                    case RequestStatusEnum.WaitingForAction:
                        <td> @Html.ActionLink("Gotowy do odbioru", "Prepared", "Requests", new { id = req.Id }, null)</td>
                        break;
                    case RequestStatusEnum.WaitingForCollection:
                        <td>@Html.ActionLink("Odebrano", "Collected", "Requests", new { id = req.Id }, null)</td>
                        break;
                    case RequestStatusEnum.InUse:
                        <td>@Html.ActionLink("Przekaż innemu kontrolerowi", "ReassignDeviceForm", "Reassignments", new { id = req.Id }, null)</td>
                        <td>@Html.ActionLink("Przyjmij na stan", "CommentForm", "Requests", new { id = req.Id }, null)</td>
                        break;
                    case RequestStatusEnum.Completed:
                        <td>Proces zakończony</td>
                        break;
                }
                
                


            </tr>
        }

    </tbody>

    </table>
@section scripts{

 <script type="text/javascript" src="@Url.Content("/scripts/CustomScripts/dtablescript.js")"></script>

}

OTDM/Views/Requests/Index_Auditor.cshtml
@using OTDM.Models
@using Microsoft.AspNet.Identity;
@model IEnumerable<Request>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Wszystkie zamówienia</h2>

    <table class="dtable table table-striped table-hover table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Numer zamówienia</th>
            <th>Nazwa urządzenia</th>
            <th>Status</th>
            <th>Przekazania</th>
            <th>Akcje do podjęcia</th>
        </tr>

    </thead>

    <tbody>

        @foreach (var req in Model)
        {
            <tr>
                <td>@req.Id</td>
                <td>@req.RequestedDevice.Name</td>
                <td>@req.RequestStatus</td>
                <td>@Html.ActionLink("Zobacz", "ReassignmentsHistory", "Reassignments", new { id = req.Id }, null)</td>
                @switch (req.RequestStatus)
                {
                    case RequestStatusEnum.WaitingForAction:
                        <td>Oczekuje na realizacje</td>
                        break;
                    case RequestStatusEnum.WaitingForCollection:
                        <td>Oczekuje na odbiór przez kontrolera</td>
                        break;
                    case RequestStatusEnum.InUse:
                        <td>
                            <span>W użytku</span>
                        </td>
                        break;
                    case RequestStatusEnum.Completed:
                        <td>Proces zakończony</td>
                        break;
                }
                
                


            </tr>
        }

    </tbody>

    </table>

@section scripts{

    <script type="text/javascript" src="@Url.Content("/scripts/CustomScripts/dtablescript.js")"></script>

}

OTDM/Views/Requests/Index_Requester.cshtml
@using OTDM.Models
@using Microsoft.AspNet.Identity;
@model IEnumerable<Request>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Wszystkie zamówienia</h2>

    <table class="dtable table table-striped table-hover table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Numer zamówienia</th>
            <th>Nazwa urządzenia</th>
            <th>Status</th>
            <th>Pzrekazania</th>
            <th>Akcje do podjęcia</th>
        </tr>

    </thead>

    <tbody>

        @foreach (var req in Model)
        {
            <tr>
                <td>@req.Id</td>
                <td>@req.RequestedDevice.Name</td>
                <td>@req.RequestStatus</td>
                <td>@Html.ActionLink("Zobacz", "ReassignmentsHistory", "Reassignments", new { id = req.Id }, null)</td>
                @switch (req.RequestStatus)
                {
                    case RequestStatusEnum.WaitingForAction:
                        <td>Oczekuje na realizacje</td>
                        break;
                    case RequestStatusEnum.WaitingForCollection:
                        <td>Oczekuje na odbiór przez kontrolera</td>
                        break;
                    case RequestStatusEnum.InUse:
                        <td>                    
                            @if (User.Identity.GetUserId() == req.RequesterId)
                            {
                                <span>@Html.ActionLink("Przekaż innemu kontrolerowi", "ReassignDeviceForm", "Reassignments", new { id = req.Id }, null)</span>

                            }
                            else
                            {
                                <span>W użytku</span>
                            }
                        </td>
                        break;
                    case RequestStatusEnum.Completed:
                        <td>Proces zakończony</td>
                        break;
                }
                


            </tr>
        }

    </tbody>

    </table>

@section scripts{

    <script type="text/javascript" src="@Url.Content("/scripts/CustomScripts/dtablescript.js")"></script>

}

OTDM/Views/Requests/RequestDevice.cshtml
@model OTDM.Models.ViewModels.RequestFormViewModel
@{
    ViewBag.Title = "Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Zamawianie urządzenia</h2>

@using (Html.BeginForm("CreateRequest", "Requests"))
{
    <div class="form-group">
        
        @Html.LabelFor(m=>m.RequesterName)
        @Html.TextBoxFor(m=>m.RequesterName, new { @class = "form-control", @readonly= ""  })
        @Html.ValidationMessageFor(m=>m.RequesterName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m=>m.DeviceName)
        @Html.TextBoxFor(m => m.DeviceName, new { @class = "form-control", @readonly = "" })
        @Html.ValidationMessageFor(m=>m.DeviceName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Request.OrderId)
        @Html.TextBoxFor(m => m.Request.OrderId, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Request.OrderId)
    </div>
    <div class="datetimer form-group">
        @Html.LabelFor(m=>m.Request.StartingDate)
        @Html.TextBoxFor(m=>m.Request.StartingDate, new { @class="datetimepicker form-control" })
        @Html.ValidationMessageFor(m => m.Request.StartingDate)
    </div>

    <div class="datetimer form-group">
        @Html.LabelFor(m => m.Request.EstimatedUsageTime)
        @Html.TextBoxFor(m => m.Request.EstimatedUsageTime, new { @class = "datetimepicker form-control" })
        @Html.ValidationMessageFor(m => m.Request.EstimatedUsageTime)
    </div>
    @Html.HiddenFor(m=>m.Request.Id)
    @Html.HiddenFor(m => m.Request.RequesterId)
    @Html.HiddenFor(m => m.Request.RequestedDeviceId)
    <button type="submit" class="btn btn-primary">Zapisz</button> @Html.ActionLink("Anuluj", null, null, null, new { href = Request.UrlReferrer, @class = "btn btn-warning" })
}

@section scripts{

    <script type="text/javascript" src="@Url.Content("/scripts/CustomScripts/datetimepicker.js")"></script>

}