OTDM/Models/Device.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using OTDM.Models.Validations;

namespace OTDM.Models
{
    public class Device
    {
        public int Id                           { get; set; }

        [Required]
        [Display(Name="Nazwa urządzenia")]
        public string Name                      { get; set; }

        [Required]
        //[SringChecker]
        [Display(Name="Kod urządzenia")]
        public string Code                      { get; set; }

       
        public DevCategory DeviceCategory       { get; set; }

        //[Required(ErrorMessage = "Please provide category of this device")]
        [Display(Name="Kategoria urządzenia")]
        public int DeviceCategoryId             { get; set; }

        public bool IsValidated                 { get; set; }

        [Required]
        [Display(Name="Data następnej walidacji")]
        public DateTime? NextValidationDate      { get; set; }

        public bool IsAvailable                 { get; set; } = true;

        public string UserId                    { get; set; }

        public ApplicationUser User             { get; set; }
    }
}

OTDM/Models/ViewModels/DeviceHistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OTDM.Models.ViewModels
{
    public class DeviceHistoryViewModel
    {
        public IEnumerable<Request> RequestsList { get; set; }
        public IEnumerable<Problem> ProblemsList { get; set; }
    }
}

OTDM/Controllers/Api/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using OTDM.Models;
using OTDM.Models.ViewModels;
using OTDM.Dtos;
using AutoMapper;
using System.Data.Entity;

namespace OTDM.Controllers.Api
{
    public class DevicesController : ApiController
    {
        private ApplicationDbContext _context;

        public DevicesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET /api/Devices
        public IHttpActionResult GetDevices()
        {
            return Ok(_context.Devices.Include(d =>d.DeviceCategory).ToList().Select(Mapper.Map<Device, DeviceDto>));
        }
        //GET /api/Devices/id

        public IHttpActionResult GetDevice(int id)
        {
            var device = _context.Devices.Include(d => d.DeviceCategory).SingleOrDefault(d => d.Id == id);
            if (device == null)
                return NotFound();
            else
                return Ok(Mapper.Map<Device, DeviceDto>(device));
        }

        //POST /api/Devices/
        [HttpPost]
        public IHttpActionResult CreateDevice(DeviceDto deviceDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            _context.Devices.Add(Mapper.Map<DeviceDto, Device>(deviceDto));
            _context.SaveChanges();

            return Created(new Uri(Request.RequestUri + "/" + deviceDto.Id), deviceDto);
        }   
            
        //PUT /api/Devices/id
        [HttpPut]
        public IHttpActionResult UpdateDevice(DeviceDto deviceDto, int id)
        {
            if (!ModelState.IsValid)
            {
                BadRequest();
            }
            else
            {
                var deviceInDb = _context.Devices.SingleOrDefault(d => d.Id == id);
                if (deviceInDb == null)
                {
                    NotFound();
                }
                Mapper.Map(deviceDto, deviceInDb);

                _context.SaveChanges();
              
            }

            return Ok((Request.RequestUri + "/" + id));
        }

        //DELETE /api/Devices/id
        [HttpDelete]
        public IHttpActionResult DeleteDevice(int id)
        {
            var device = _context.Devices.Single(d => d.Id == id);

            _context.Devices.Remove(device);
            _context.SaveChanges();
            return Ok("Removed");
        }
    }
}

OTDM/Controllers/ProblemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTDM.Models;
using OTDM.Models.ViewModels;
using Microsoft.AspNet.Identity;
using OTDM.Util;
using System.Data.Entity;

namespace OTDM.Controllers
{
    [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager + "," + RoleName.TechnicalInvestigator + "," + RoleName.Auditor)]
    public class ProblemsController : Controller
    {
        private ApplicationDbContext _context;
        public ProblemsController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Histories
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager + "," + RoleName.TechnicalInvestigator)]
        public ActionResult ReportProblem(int id)
        {
            if (!_context.Devices.SingleOrDefault(d => d.Id == id).IsValidated)
                throw new InvalidOperationException("Ten tester nie został jeszcze dopuszcozny do użytku lub jest obecnie sprawdzany przez zespół techniczny");
            var viewModel = new ReportProblemViewModel
            {
               
                Problem = new Problem
                {
                    DeviceId = id,
                    ReportingDate = DateTime.Now,
                    ReporterId = User.Identity.GetUserId()
                },

                ReporterName = User.Identity.GetUserName(),
                ProblematicDeviceName = _context.Devices.SingleOrDefault(d => d.Id == id).Name
            };
            return View(viewModel);
        }


        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager + "," + RoleName.TechnicalInvestigator)]
        [HttpPost]
        public ActionResult CreateProblem (ReportProblemViewModel viewModel)
        {
            if (!_context.Devices.SingleOrDefault(d => d.Id == viewModel.Problem.DeviceId).IsValidated)
                throw new InvalidOperationException("Ten tester nie został jeszcze dopuszcozny do użytku lub jest obecnie sprawdzany przez zespół techniczny w związku ze zgłoszeniem");
            else if (!ModelState.IsValid)
            {
                return View("ReportProblem", viewModel);
            }

            _context.Problems.Add(viewModel.Problem);
            _context.Devices.SingleOrDefault(d => d.Id == viewModel.Problem.DeviceId).IsValidated = false;
            _context.SaveChanges();

            MailSender.SendMail(GroupMails.QualityGroupMail, GroupMails.Technician, "Problem z urządzeniem " + viewModel.Problem.Device.Code,
                                viewModel.ReporterName + " zgłosił problem z urządzeniem: " +viewModel.Problem.Device.Name + " - " + viewModel.Problem.Device.Code + ". " + "</br></br>" + "<b>Opis problemu: </b></br>" + "<i>" + viewModel.Problem.ProblemDescription + "</i>");

            return RedirectToAction("Index", "Devices");
        }

        public ActionResult ResolutionForm(int id)
        {
            if (_context.Problems.Any(p => p.Id == id && p.ProblemStatus == ProblemStatusEnum.Resolved))
                throw new InvalidOperationException("Ten problem został już rozwiązany");
            var viewModel = new ResolutionFormViewModel
            {
                ProblemId = id
            };
            return View(viewModel);
        }

        public ActionResult ResolveProblem(ResolutionFormViewModel viewModel)
        {
            if (_context.Problems.Any(p => p.Id == viewModel.ProblemId && p.ProblemStatus == ProblemStatusEnum.Resolved))
                throw new InvalidOperationException("Ten problem został już rozwiązany");
            var problemInDb = _context.Problems.Include(p=>p.Device).SingleOrDefault(p => p.Id == viewModel.ProblemId);
            var problematicDevice = _context.Devices.SingleOrDefault(d => d.Id == problemInDb.DeviceId);
            
            problemInDb.ProblemStatus = ProblemStatusEnum.Resolved;
            problemInDb.ResolverId = User.Identity.GetUserId();
            problemInDb.ResolutionDate = DateTime.Now;
            problemInDb.ResolutionDescription = viewModel.Problem.ResolutionDescription;
            problematicDevice.IsValidated = true;
            _context.SaveChanges();

            MailSender.SendMail(GroupMails.Technician, GroupMails.ProductionGroupMail + "," + GroupMails.QualityGroupMail, "Problem nr: " + problemInDb.Id + " został rozwiązany",
                "Problem z urządzeniem: " + problemInDb.Device.Name + " - " + problemInDb.Device.Code + " został rozwiązany. </br></br>" + "<b>Opis problemu: </b></br>" + "<i>" + problemInDb.ProblemDescription + "</i>.</br></br><b> Opis rozwiązania: </b></br>" + "<i>" + problemInDb.ResolutionDescription + ".</i>");

            return RedirectToAction("MyActivities", "Activities");
        }

        
    }
}

OTDM/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTDM.Models;
using OTDM.Models.ViewModels;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using OTDM.Util;

namespace OTDM.Controllers
{
    [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager + "," + RoleName.Auditor + "," + RoleName.TechnicalInvestigator)]
    public class RequestsController : Controller
    {

        private ApplicationDbContext _context;

        public RequestsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        public ActionResult Index()
        {
            var requestsList = _context.Requests.Include("RequestedDevice").ToList();
            if (User.IsInRole(RoleName.Admin))
                return View("Index_Admin", requestsList);
            else if (User.IsInRole(RoleName.Auditor))
                return View("Index_Auditor", requestsList);
            else return View("Index_Requester", requestsList);
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult RequestDevice(int? id)
        {

            if (id == null)
                return RedirectToAction("Index");

            else if (!_context.Devices.SingleOrDefault(d => d.Id == id).IsValidated || _context.Devices.SingleOrDefault(d=>d.Id == id).NextValidationDate <= DateTime.Now)
                throw new InvalidOperationException("Tester nie został jeszcze zwalidowany lub jest sparwdzany przez dział techniczny w związku ze zgłoszoniem problemu");

            else if (_context.Requests.Any(r => r.RequestedDeviceId == id && r.RequestStatus != RequestStatusEnum.Completed))
                throw new InvalidOperationException("Ten tester jest obecnie w użyciu");

            else
            {
                var viewModel = new RequestFormViewModel
                {
                    Request = new Request
                    {
                        RequestedDeviceId = (int)id,
                        RequesterId = User.Identity.GetUserId()
                    },     
                    
                    RequesterName = User.Identity.GetUserName(),
                    DeviceName = _context.Devices.SingleOrDefault(d => d.Id == id).Name

                };
                return View(viewModel);
            }      
            
        }
        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult CreateRequest(RequestFormViewModel viewModel)
        {
            var deviceInDb = _context.Devices.SingleOrDefault(d => d.Id == viewModel.Request.RequestedDeviceId);
            if ((_context.Requests.Any(r => r.RequestedDeviceId == viewModel.Request.RequestedDeviceId && r.RequestStatus != RequestStatusEnum.Completed)))
                throw new InvalidOperationException("Ten tester jest obecnie w użyciu");
            else if (!ModelState.IsValid)
            {
                var validatedViewModel = new RequestFormViewModel();
                validatedViewModel = viewModel;
                return View("RequestDevice", validatedViewModel);
            }

            _context.Requests.Add(viewModel.Request);
            _context.SaveChanges();

            MailSender.SendMail(GroupMails.ProductionGroupMail, GroupMails.QualityGroupMail, "Prośba o przygotowanie urządzenia",
                                viewModel.RequesterName + " poprosił o przygotowanie urządzenia: " + viewModel.DeviceName + " - " +viewModel.Request.RequestedDevice.Code + " w związku ze zleceniem produkcyjnym: " + viewModel.Request.OrderId +
                                ". Czas rozpoczęcia produkcji: " + viewModel.Request.StartingDate + ". Estymowany czas zakonczenia użytkowania: " + viewModel.Request.EstimatedUsageTime);

            return RedirectToAction("Index", "Devices");
        }

        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Prepared(int id)
        {
            var requestInDb = _context.Requests.Include(r=>r.RequestedDevice).SingleOrDefault(r => r.Id == id);
            if (requestInDb.RequestStatus != RequestStatusEnum.WaitingForAction)
                throw new InvalidOperationException("Niepoprawna operacja");
            else
            {
                requestInDb.RequestStatus = RequestStatusEnum.WaitingForCollection;
                requestInDb.GiverId = User.Identity.GetUserId();
            }

            _context.SaveChanges();

            MailSender.SendMail(GroupMails.QualityGroupMail, GroupMails.ProductionGroupMail, "Urządzenie oczekuje na odbiór", 
                "Urządzenie: " + requestInDb.RequestedDevice.Name + " o kodzie: " + requestInDb.RequestedDevice.Code + " zamówione do zlecenia produkcyjnego: " + requestInDb.OrderId + " oczekuje na odbiór lidera.");

            return RedirectToAction("MyActivities", "Activities");
        }

        [Authorize(Roles = RoleName.Admin + "," + RoleName.QualityManager)]
        public ActionResult Collected(int id)
        {
            if (_context.Requests.Any(r => r.Id == id && r.RequestStatus != RequestStatusEnum.WaitingForCollection))
                throw new InvalidOperationException("Niepoprawna operacja");
            else
            {
                var requestInDb = _context.Requests.SingleOrDefault(r => r.Id == id);
                requestInDb.RequestStatus = RequestStatusEnum.InUse;
                
            }
            _context.SaveChanges();
            return RedirectToAction("MyActivities", "Activities");
        }

        [Authorize(Roles = RoleName.Admin)]
        public ActionResult CommentForm(int id)
        {
            if (_context.Requests.Any(r => r.Id == id && r.RequestStatus == RequestStatusEnum.Completed))
                throw new InvalidOperationException("To zamówienie zostało już zakonczone");
            else
            {
                var viewModel = new RequestCompletetedCommentViewModel
                {
                    RequestId = id,

                };
                return View(viewModel);
            }
                
        }

        [Authorize(Roles = RoleName.Admin)]
        public ActionResult UnblockDevice(RequestCompletetedCommentViewModel viewModel)
        {
            if (_context.Requests.Any(r => r.Id == viewModel.RequestId && r.RequestStatus == RequestStatusEnum.Completed))
                throw new InvalidOperationException("To zamówienie zostało już zakonczone");
            else
            {
                var requestInDb = _context.Requests.SingleOrDefault(r => r.Id == viewModel.RequestId);
                requestInDb.RequestStatus = RequestStatusEnum.Completed;
                requestInDb.ReceiverId = User.Identity.GetUserId();
                requestInDb.EndDate = DateTime.Now;
                requestInDb.Comment = viewModel.Request.Comment;

                _context.SaveChanges();

            }
            return RedirectToAction("MyActivities", "Activities");


        }

      
    }
}

OTDM/Views/Devices/Details.cshtml
@model OTDM.Models.Device
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>

OTDM/Views/Devices/Index_Admin.cshtml
@using Microsoft.AspNet.Identity;
@using OTDM.Models;
@model OTDM.Models.ViewModels.DevicesIndexViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2>Lista urządzeń</h2>
    @Html.ActionLink("Dodaj urządzenie", "New", "Devices", null, new { @class = "btn btn-success" })
    <br><br>
    @if (Model == null || !Model.DevicesList.Any())
    {
        <p>Brak urządzeń w bazie danych</p>
    }
    else
    {
        <table class="dtable table table-striped table-bordered nowrap" cellspacing="0" style="width: 100%;">
            <thead class="thead-dark">
                <tr>
                    <th>Nazwa urządzenia</th>
                    <th>Kod urządzenia</th>
                    <th>Kategoria urządzenia</th>
                    <th>Status</th>
                    <th>Akcje</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var device in Model.DevicesList)
                {
                    <tr>
                        <td>@Html.ActionLink(device.Name, "Details", "Devices", new { id = device.Id }, new { @class = "deviceclass" })</td>
                        <td>@device.Code</td>
                        <td>@device.DeviceCategory.Name</td>

                        @if (@Model.RequestsList.Any(r => r.RequestedDeviceId == device.Id))
                        {
                            <td>
                                <span class="label label-danger">Niedostępny</span>
                                <span class="label label-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Obecnie użytkowany przez @Model.ViewUserManager.FindById(Model.RequestsList.SingleOrDefault(r => r.RequestedDeviceId==device.Id).RequesterId).FullName. Przewidywany czas zwrotu: @Model.RequestsList.SingleOrDefault(r => r.RequestedDeviceId == device.Id).EstimatedUsageTime">Info</span>
                            </td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Edytuj">@Html.ActionLink(" ", "Edit", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-edit", style = "margin-right: 5px; color: orange; text-decoration: none;" })</span>
                                    <span id = @device.Id data-toggle="tooltip" data-placement="top" title="" data-original-title="Usuń" class = "js-delete glyphicon glyphicon-trash" style = "margin-right: 5px; color: red; text-decoration: none;"></span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Zgłoś problem">@Html.ActionLink(" ", "ReportProblem", "Problems", new { id = device.Id }, new { @class = "glyphicon glyphicon-bullhorn", style = "margin-right: 5px; color: purple; text-decoration: none;" })</span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>
                        }
                        else if (!device.IsValidated)
                        {
                            <td>
                                <span class="label label-danger">Niedostępny</span>
                                <span class="label label-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Urządzenie jest obecnie walidowane/naprawiane">Info</span>
                            </td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Edytuj">@Html.ActionLink(" ", "Edit", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-edit", style = "margin-right: 5px; color: orange; text-decoration: none;" })</span>
                                    <span id=@device.Id data-toggle="tooltip" data-placement="top" title="" data-original-title="Usuń" class="js-delete glyphicon glyphicon-trash" style="margin-right: 5px; color: red; text-decoration: none;"></span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>

                        }

                        else if (device.NextValidationDate <= DateTime.Now)
                        {
                            <td>
                                <span class="label label-warning">Wymaga walidacji</span>
                                <span class="label label-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Zalecana akcja: 'zgłoś problem'">Info</span>
                            </td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Edytuj">@Html.ActionLink(" ", "Edit", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-edit", style = "margin-right: 5px; color: orange; text-decoration: none;" })</span>
                                    <span id=@device.Id data-toggle="tooltip" data-placement="top" title="" data-original-title="Usuń" class="js-delete glyphicon glyphicon-trash" style="margin-right: 5px; color: red; text-decoration: none;"></span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Zgłoś problem">@Html.ActionLink(" ", "ReportProblem", "Problems", new { id = device.Id }, new { @class = "glyphicon glyphicon-bullhorn", style = "margin-right: 5px; color: purple; text-decoration: none;" })</span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>

                        }

                        else
                        {
                            <td><span class="label label-success">Dostępny</span></td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Edytuj">@Html.ActionLink(" ", "Edit", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-edit", style = "margin-right: 5px; color: orange; text-decoration: none;" })</span>
                                    <span id=@device.Id data-toggle="tooltip" data-placement="top" title="" data-original-title="Usuń" class="js-delete glyphicon glyphicon-trash" style="margin-right: 5px; color: red; text-decoration: none;"></span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Zamów">@Html.ActionLink(" ", "RequestDevice", "Requests", new { id = device.Id }, new { @class = "glyphicon glyphicon-list-alt", style = "margin-right: 5px; color: green; text-decoration: none;" })</span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Zgłoś problem">@Html.ActionLink(" ", "ReportProblem", "Problems", new { id = device.Id }, new { @class = "glyphicon glyphicon-bullhorn", style = "margin-right: 5px; color: purple; text-decoration: none;" })</span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>
                        }


                    </tr>
                }
            </tbody>

        </table>
    }

    @section scripts{

        <script type="text/javascript" src="@Url.Content("/scripts/CustomScripts/dtablescript.js")"></script>

    }

OTDM/Views/Devices/Index_Auditor.cshtml
@using Microsoft.AspNet.Identity;
@using OTDM.Models;
@model OTDM.Models.ViewModels.DevicesIndexViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista urządzeń </h2>

<br><br>
@if(Model==null || !Model.DevicesList.Any())
{
    <p>Brak urządzeń w bazie</p>
}
else
{
    <table class="dtable table table-striped table-bordered nowrap" cellspacing="0" style="width: 100%;">
        <thead class="thead-dark">
            <tr>
                <th>Nazwa urządzenia</th>
                <th>Kod urządzenia</th>
                <th>Kategoria urządzenia</th>
                <th>Status</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var device in Model.DevicesList)
            {
                <tr>
                    <td>@Html.ActionLink(device.Name, "Details", "Devices", new { id = device.Id }, new { @class = "deviceclass" })</td>
                    <td>@device.Code</td>
                    <td>@device.DeviceCategory.Name</td>
                    @if (@Model.RequestsList.Any(r => r.RequestedDeviceId == device.Id))
                    {
                        <td>
                            <span class="label label-danger">Niedostępny</span>
                            <span class="label label-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Obecnie użytkowany przez @Model.ViewUserManager.FindById(Model.RequestsList.SingleOrDefault(r => r.RequestedDeviceId==device.Id).RequesterId).FullName. Przewidywany czas zwrotu: @Model.RequestsList.SingleOrDefault(r => r.RequestedDeviceId == device.Id).EstimatedUsageTime">Info</span>
                        </td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>
                    }
                    else if (!device.IsValidated)
                    {
                        <td>
                            <span class="label label-danger">Niedostępny</span>
                            <span class="label label-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Urządzenie jest obecnie walidowane/naprawiane">Info</span>
                        </td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>

                    }

                    else if (device.NextValidationDate<= DateTime.Now)
                    {
                            <td>
                                <span class="label label-warning">Wymaga walidacji</span>
                                <span class="label label-info" data-toggle="tooltip" data-placement="top" title="" data-original-title="Zalecana akcja: 'zgłoś problem'">Info</span>
                            </td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Zgłoś problem">@Html.ActionLink(" ", "ReportProblem", "Problems", new { id = device.Id }, new { @class = "glyphicon glyphicon-bullhorn", style = "margin-right: 5px; color: purple; text-decoration: none;" })</span>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>

                    }

                    else
                    {
                        <td><span class="label label-success">Dostępny</span></td>
                            <td>
                                <div>
                                    <span data-toggle="tooltip" data-placement="top" title="" data-original-title="Historia">@Html.ActionLink(" ", "DeviceHistory", "Devices", new { id = device.Id }, new { @class = "glyphicon glyphicon-time", style = "margin-right: 5px; color: black; text-decoration: none;" })</span>
                                </div>
                            </td>
                    }
                </tr>
            }
        </tbody>

    </table>
}


@section scripts{

    <script type="text/javascript" src="@Url.Content("/scripts/CustomScripts/dtablescript.js")"></script>

}